version: "3"
services:
  mcod-jupyter:
    container_name: mcod-jupyter
    image: registry.dane.gov.pl/mcod/lab/lab:latest
    ports:
      - 8888:8888
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_BASE_URL=jupyter
      - JUPYTER_PORT=8888
      - JUPYTER_TOKEN=Britenet.1
      - JUPYTER_ALLOW_ORIGIN=*
    volumes:
      - $PWD/notebooks/notebooks:/home/jovyan/notebooks
    command: "/usr/local/bin/start-jupyter"

  mcod-panel:
    container_name: mcod-panel
    image: registry.dane.gov.pl/mcod/lab/lab:latest
    ports:
      - 8890:8890
    environment:
      - GRANT_SUDO=yes
      - BOKEH_PORT=8890
      - BOKEH_BASE_URL=viz
      - BOKEH_ALLOW_WS_ORIG=localhost,mcod.local
    volumes:
      - $PWD/notebooks/notebooks:/home/jovyan/notebooks:ro
    command: "/usr/local/bin/start-panel"

  mcod-apm:
    image: docker.elastic.co/apm/apm-server:6.7.2
    container_name: mcod-apm
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    command: >
      apm-server -e
       -E apm-server.rum.enabled=true
       -E apm-server.host=0.0.0.0:8200
       -E setup.kibana.host=mcod-kibana:5601
       -E setup.template.settings.index.number_of_replicas=0
       -E apm-server.kibana.enabled=true
       -E apm-server.kibana.host=mcod-kibana:5601
       -E output.elasticsearch.hosts=["mcod-elasticsearch:9200"]
       -E apm-server.host=0.0.0.0:8200

  mcod-flower:
    image: mher/flower
    container_name: mcod-flower
    environment:
      - CELERY_BROKER_URL=amqp://mcod-rabbitmq:5672
      - FLOWER_PORT=8888
    ports:
      - 8888:8888

  mcod-kibana:
    image: docker.elastic.co/kibana/kibana:6.7.2
    container_name: mcod-kibana
    environment:
      SERVER_NAME: kibana.mcod.local
      ELASTICSEARCH_URL: http://mcod-elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://mcod-elasticsearch:9200
    ports:
      - 5601:5601

  mcod-smtp:
    container_name: mcod-smtp
    image: mailhog/mailhog
    user: root
    ports:
      - 8025:8025
      - 1025:1025
    healthcheck:
      test: echo | telnet 127.0.0.1 1025

networks:
  default:
    external:
      name: backend_backend
