[pytest]
python_files = tests.py test_*.py *_tests.py
addopts = --reuse-db --ds=mcod.settings.test -n3
markers =
    component_cms: test requires COMPONENT=cms
    component_api: test requires COMPONENT=api
    depends_on_component: test requires a specific COMPONENT
