# Generated by Django 2.2.9 on 2026-03-09 11:48

from django.db import migrations
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("showcases", "0007_auto_20241029_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcase",
            name="author",
            field=mcod.lib.model_sanitization.SanitizedCharField(blank=True, max_length=300, null=True, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="author",
            field=mcod.lib.model_sanitization.SanitizedCharField(blank=True, max_length=300, null=True, verbose_name="Author"),
        ),
    ]
