# Generated by Django 2.2.9 on 2026-05-04 19:34

import django.contrib.postgres.fields
from django.db import migrations, models
import mcod.lib.model_sanitization


class Migration(migrations.Migration):

    dependencies = [
        ("showcases", "0008_auto_20260309_1248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showcase",
            name="url",
            field=models.URLField(max_length=2048, null=True, verbose_name="App URL"),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=mcod.lib.model_sanitization.SanitizedCharField(max_length=300),
                default=list,
                size=None,
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="showcaseproposal",
            name="url",
            field=models.URLField(max_length=2048, null=True, verbose_name="App URL"),
        ),
    ]
