{% load i18n %}
---
tags:
   - {% trans "API Endpoints" %}
summary: {% trans "Get single application" %}
description: |
  {% spaceless %}
      <p>Returns application with given ID.</p>
      {% include "docs/applications/obj_description.html" %}
  {% endspaceless %}
parameters:
    schema: ApplicationApiRequest
responses:
    200:
        description: valid response in jsonapi format
        content:
            application/vnd.api+json:
                schema:
                    $ref: '#/components/schemas/Application'
