# Generated by Django 2.2.9 on 2026-04-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0033_auto_20241029_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accepteddatasetsubmission",
            name="organization_name",
            field=models.CharField(blank=True, max_length=300, verbose_name="Institution name"),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="organization_name",
            field=models.CharField(blank=True, max_length=300, verbose_name="Institution name"),
        ),
    ]
