# Generated by Django 2.2.9 on 2026-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0034_auto_20260428_0909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accepteddatasetsubmission",
            name="data_link",
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name="Link to data"),
        ),
        migrations.AlterField(
            model_name="datasetsubmission",
            name="data_link",
            field=models.URLField(blank=True, max_length=2048, null=True, verbose_name="Link to data"),
        ),
    ]
