BEGIN;

/* 1. ADD COLUMN entry_timestamp i entry_operator */
ALTER TABLE "application"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;
ALTER TABLE "application_tag"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;
ALTER TABLE "application_dataset"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "article"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;
ALTER TABLE "article_tag"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;
ALTER TABLE "article_dataset"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;


ALTER TABLE "dataset"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;
ALTER TABLE "dataset_tag"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;



ALTER TABLE "resource"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "category"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "organization"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "user"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "user_following_application"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "user_following_article"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "user_following_dataset"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;

ALTER TABLE "tag"
    ADD entry_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD entry_operator VARCHAR(50) DEFAULT CURRENT_USER NOT NULL;


COMMIT;