# Generated by Django 2.2.9 on 2026-06-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("histories", "0010_delete_triggers"),
        ("users", "0020_user_agent_organizations_history_trigger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="History",
        ),
    ]
