# Generated by Django 2.2.9 on 2026-05-30 21:49

from django.db import migrations, models
import mcod.submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubmissionEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            (mcod.submissions.models.Subject("DATA"), "Dane"),
                            (mcod.submissions.models.Subject("PORTAL"), "Portal dane.gov.pl"),
                            (mcod.submissions.models.Subject("DATA_PROTECTION"), "Ochrona danych osobowych w portalu"),
                            (mcod.submissions.models.Subject("LEGAL"), "Regulacje prawne dotyczące otwartości danych"),
                            (mcod.submissions.models.Subject("OTHER"), "Inne"),
                        ],
                        max_length=32,
                        verbose_name="Submission subject",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            (mcod.submissions.models.Category("SHARING"), "Udostępnianie danych w portalu"),
                            (mcod.submissions.models.Category("SUGGEST_DATA"), "Zaproponuj dane do udostępnienia w portalu"),
                            (
                                mcod.submissions.models.Category("SUGGEST_REUSE"),
                                "Zaproponuj przykład ponownego wykorzystania danych",
                            ),
                            (mcod.submissions.models.Category("FEEDBACK"), "Zgłoś uwagi do danych udostępnionych w portalu"),
                            (mcod.submissions.models.Category("STANDARDS"), "Standardy otwartości danych"),
                            (mcod.submissions.models.Category("HVD"), "Dane o wysokiej wartości (HVD)"),
                            (mcod.submissions.models.Category("DGA"), "Chronione dane (DGA)"),
                            (mcod.submissions.models.Category("FEATURES"), "Funkcjonalności portalu"),
                            (mcod.submissions.models.Category("PROFILES"), "Zakładanie profili dostawców"),
                            (mcod.submissions.models.Category("PERMISSIONS"), "Nadawanie uprawnień"),
                            (mcod.submissions.models.Category("BUGS"), "Błędy w działaniu portalu"),
                            (mcod.submissions.models.Category("OTHER"), "Inne"),
                        ],
                        max_length=32,
                        verbose_name="Submission category",
                    ),
                ),
                ("submission_date", models.DateTimeField(verbose_name="Submission date")),
            ],
            options={
                "verbose_name": "Submission Event",
                "verbose_name_plural": "Submission Events",
            },
        ),
    ]
