# Generated by Django 2.2.9 on 2026-06-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionevent",
            name="reference_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.ContentType",
                verbose_name="Reference content type",
            ),
        ),
        migrations.AddField(
            model_name="submissionevent",
            name="reference_object_id",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Reference object id"),
        ),
        migrations.AddIndex(
            model_name="submissionevent",
            index=models.Index(fields=["reference_content_type", "reference_object_id"], name="subm_evt_ref_ct_oid_idx"),
        ),
    ]
